- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Medical
  #   min: 28800
  # WD EDIT END
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - Government
    - Contractors
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External
  - Paramedic
  #SS14RU-start
  - Command
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - ResearchDirector
  - Quartermaster
  - Bar
  - Service
  - Janitor
  - Theatre
  - Kitchen
  - Hydroponics
  - Cryogenics
  - Lawyer
  - Cargo
  - Boxer
  - Clown
  - Library
  - Mime
  - Musician
  - Reporter
  - Zookeeper
  - Atmospherics
  - Chemistry
  - Chapel
  - Engineering
  - Research
  - Salvage
  - Mail
  - Psychologist
  - Corpsman
#SS14RU-end
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 2 # WD EDIT

- type: startingGear
  id: ParamedicGear
  subGear:
  - ParamedicPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorBlue
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
#SS14RU-start
    outerClothing: ClothingOuterHardsuitVoidParamed
    belt: ClothingBeltMedicalEMTFilled
    pocket1: WeaponPistolMk58
    # pocket2: HandheldCrewMonitor
#SS14RU-end
  storage:
    back:
    - MagazinePistolSubMachineGun
    - WeaponSubMachineGunDrozd
    - MagazinePistol
    - BodyBagFolded
    # - Portafib

- type: startingGear
  id: ParamedicPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitParamedic
    head: ClothingHeadEnvirohelmParamedic
    gloves: ClothingHandsGlovesEnviroglovesNitrile
