- type: job
  id: CnsCommander
  name: jon-name-cns-commander
  description: jon-description-cns-commander
  playTimeTracker: JobCnsCommander
  setPreference: true
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 54000 # 15 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - BrittleBoneDisease
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen # BSO works directly for centcomm, they are not a contractor.
    - !type:CharacterOverallTimeRequirement # WWDP
      min: 7200
  weight: 25
  startingGear: CnsCommanderGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Lawyer
  - Cargo
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ] #Force the implant since its manual activation now
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: CPRTraining
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CnsCommanderGear
  subGear:
  - CnsCommanderPlasmamanGear
  equipment:
    back: ClothingBackpackBlueshield
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetCorporations
    gloves: ClothingHandsGlovesCombat
    id: CorporationsComPDA
#    pocket1: UniqueBlueshieldOfficerLockerTeleporter
#    pocket2: BluespaceLifelineImplanter    #Doesn't need this since its implanted roundstart

    #outerClothing: ClothingBlueshieldArmourVest
    #ears: ClothingHeadsetAltCommand
    #belt: ClothingBeltSecurityFilled
    #pocket1: WeaponPistolMk58
    #pocket2: DeathAcidifierImplanter

- type: startingGear
  id: CnsCommanderPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBlueshield
    head: ClothingHeadEnvirohelmBlueshield
    gloves: ClothingHandsGlovesEnviroglovesBlack
