- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  setPreference: true
  requirements:
    # SS14 RU START
    - !type:CharacterPlaytimeRequirement
      tracker: JobWarden
      min: 21600 #6 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobDetective
      min: 7200 #2 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobSecurityOfficer
      min: 21600 #6 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 216000 # 60 hrs
    # SS14 RU END
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - BrittleBoneDisease
    - !type:CharacterEmployerRequirement
      employers:
      - ZavodskoiInterstellar
      - PMCG
      - NanoTrasen
      - EastOrionCompany
    # SS14 RU START
    - !type:CharacterOverallTimeRequirement
      min: 3600
    # SS14 RU END
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: SeniorOfficerGear
  subGear:
  - SecurityOfficerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorOfficer
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack # SS14 RU: ClothingShoesBootsJackFilled -> ClothingShoesBootsJack
    # eyes: ClothingEyesGlassesSecurity - SS14 RU
    head: ClothingHeadHatBeretSecurity
    # outerClothing: ClothingOuterArmorPlateCarrier - SS14 RU
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    # belt: ClothingBeltSecurityFilled - SS14 RU
  storage:
    back:
    - WeaponEnergyGunPistolSecurity # SS14 RU
