- type: job
  id: NanotrasenRepresentative
  name: job-name-corporate-liaison
  description: "Represent your employer, send reports back to them on the station's situation, inform the heads of anything CentCom orders them to do."
  playTimeTracker: JobNanotrasenRepresentative
  setPreference: true #SS14RU-edit
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
    - !type:CharacterOverallTimeRequirement # WWDP
      min: 7200
  weight: 30 #SS14RU-edit
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Lawyer #SS14RU-edit
  - Cargo #SS14RU-edit
  - Command
  - NanotrasenRepresentative
  - CentralCommand #SS14RU-edit
  - BlueshieldOfficer #SS14RU-edit
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: NanotrasenRepresentativeGear
  subGear:
  - NanotrasenRepresentativePlasmamanGear
  equipment:
    back: ClothingBackpackSatchelNanorep #SS14RU-edit
    shoes: ClothingShoesColorBlack
    id: NanotrasenRepresentativePDA #SS14RU-edit
    jumpsuit: ClothingUniformJumpsuitNanotrasenRepresentative
    ears: ClothingHeadsetNtr #SS14RU-edit
    # pocket1: UniqueNanorepLockerTeleporter #SS14RU-edit
  #SS14RU-start
  storage:
    back:
    - RubberStampNanorep
    - Paper
    - Paper
#SS14RU-end

- type: startingGear
  id: NanotrasenRepresentativePlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitNanotrasenRepresentative
    head: ClothingHeadEnvirohelmNanotrasenRepresentative
    gloves: ClothingHandsGlovesEnviroglovesBlack
