- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobNanotrasenRepresentative

- type: playTimeTracker
  id: JobMagistrate

#SS14RU-start
- type: playTimeTracker
  id: JobBlueshieldCommander
#SS14RU-end
