using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Gravity;
using Content.Shared.Power;
using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace Content.Client.Power.PowerCharge;

[GenerateTypedNameReferences]
public sealed partial class PowerChargeWindow : FancyWindow
{
    private readonly ButtonGroup _buttonGroup = new();
    private readonly IEntityManager _entityManager = IoCManager.Resolve<IEntityManager>();
    private EntityUid _owner = EntityUid.Invalid;

    public PowerChargeWindow()
    {
        RobustXamlLoader.Load(this);

        OnButton.Group = _buttonGroup;
        OffButton.Group = _buttonGroup;
    }

    public void UpdateWindow(PowerChargeBoundUserInterface bui, string title)
    {
        Title = title;

        OnButton.OnPressed += _ => bui.SetPowerSwitch(true);
        OffButton.OnPressed += _ => bui.SetPowerSwitch(false);

        EntityView.SetEntity(bui.Owner);
        _owner = bui.Owner;
    }

    public void UpdateState(PowerChargeState state)
    {
        if (state.On)
            OnButton.Pressed = true;
        else
            OffButton.Pressed = true;

        PowerLabel.Text = Loc.GetString(
            "power-charge-window-power-label",
            ("draw", state.PowerDraw),
            ("max", state.PowerDrawMax));

        PowerLabel.SetOnlyStyleClass(MathHelper.CloseTo(state.PowerDraw, state.PowerDrawMax) ? "Good" : "Caution");

        ChargeBar.Value = state.Charge;
        ChargeText.Text = (state.Charge / 255f).ToString("P0");
        StatusLabel.Text = Loc.GetString(state.PowerStatus switch
        {
            PowerChargePowerStatus.Off => "power-charge-window-status-off",
            PowerChargePowerStatus.Discharging => "power-charge-window-status-discharging",
            PowerChargePowerStatus.Charging => "power-charge-window-status-charging",
            PowerChargePowerStatus.FullyCharged => "power-charge-window-status-fully-charged",
            _ => throw new ArgumentOutOfRangeException()
        });

        StatusLabel.SetOnlyStyleClass(state.PowerStatus switch
        {
            PowerChargePowerStatus.Off => "Danger",
            PowerChargePowerStatus.Discharging => "Caution",
            PowerChargePowerStatus.Charging => "Caution",
            PowerChargePowerStatus.FullyCharged => "Good",
            _ => throw new ArgumentOutOfRangeException()
        });

        EtaLabel.Text = state.EtaSeconds >= 0
            ? Loc.GetString("power-charge-window-eta-value", ("left", TimeSpan.FromSeconds(state.EtaSeconds)))
            : Loc.GetString("power-charge-window-eta-none");

        EtaLabel.SetOnlyStyleClass(state.EtaSeconds >= 0 ? "Caution" : "Disabled");

        var showStationStatus = TryGetStationStatus(out var stationMass, out var stationLocked);
        MassTitle.Visible = MassValue.Visible = showStationStatus;
        FtlTitle.Visible = FtlValue.Visible = showStationStatus;

        if (showStationStatus)
        {
            var roundedMass = Math.Round(stationMass, 1);
            MassValue.Text = Loc.GetString("gravity-generator-window-mass-value", ("mass", roundedMass));

            var ftlKey = stationLocked ? "gravity-generator-examine-ftl-locked" : "gravity-generator-examine-ftl-free";
            FtlValue.Text = Loc.GetString(ftlKey);
            FtlValue.SetOnlyStyleClass(stationLocked ? "Danger" : "Good");
        }
        else
        {
            MassValue.Text = "\u2014";
            FtlValue.Text = "\u2014";
            FtlValue.SetOnlyStyleClass("Disabled");
        }
    }

    private bool TryGetStationStatus(out float mass, out bool locked)
    {
        mass = 0f;
        locked = false;

        if (!_owner.IsValid())
            return false;

        if (!_entityManager.TryGetComponent(_owner, out AwsGravityGeneratorStatusComponent? status))
            return false;

        if (!status.ShowStatus)
            return false;

        mass = status.StationMass;
        locked = status.StationFtlLocked;
        return true;
    }
}